steps:
  # 1) Docker Build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--file=server/Dockerfile'
      - >-
        --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${SHORT_SHA}
      - server
    id: Build
  # 2) Docker Push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${SHORT_SHA}'
    id: Docker Push
  # 3) Deploy to Cloud Run (Secret File Mount 형식으로 수정)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE}'
      - '--image'
      - >-
        ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${SHORT_SHA}
      - '--region'
      - '${_REGION}'
      - '--platform'
      - managed
      - '--allow-unauthenticated'
      - '--set-secrets' # Secret File Mount: 경로/파일명=Secret:버전
      - |
        /etc/secrets/toss_cert/rankmyluck-mtls-cert=rankmyluck-mtls-cert:latest,
        /etc/secrets/toss_key/rankmyluck-mtls-key=rankmyluck-mtls-key:latest
      - '--set-env-vars'
      - |
        DB_HOST=${_DB_HOST},
        DB_PORT=${_DB_PORT},
        DB_USER=${_DB_USER},
        DB_PASS=${_DB_PASS},
        DB_NAME=${_DB_NAME},
        DB_SSL=${_DB_SSL},
        CORS_ORIGIN=${_CORS_ORIGIN},
        ADMIN_TOKEN=${_ADMIN_TOKEN},
        USE_DEV_FALLBACK=0,
        PAYOUT_SIMULATE=0,
        TOSS_DECRYPTION_KEY=${_TOSS_DECRYPTION_KEY},
        TOSS_KEY_FORMAT=${_TOSS_KEY_FORMAT},
        TOSS_PROMOTION_CODE=${_TOSS_PROMOTION_CODE},
        TOSS_PROMOTION_ACCESS_TOKEN=${_TOSS_PROMOTION_ACCESS_TOKEN},
        TOSS_DISCONNECT_BASIC_AUTH=${_TOSS_DISCONNECT_BASIC_AUTH},
        TOSS_MTLS_CERT_PATH=/etc/secrets/toss_cert/rankmyluck-mtls-cert,
        TOSS_MTLS_KEY_PATH=/etc/secrets/toss_key/rankmyluck-mtls-key
substitutions:
  _SERVICE: rank-my-luck
  _REPO: containers
  _IMAGE: rank-my-luck
  _REGION: us-central1
  # Cloud Build 실행 시 반드시 제공되어야 하는 변수들
  # 예시:
  # _DB_HOST: 34.123.34.118
  # _DB_PORT: '5432'
  # ... (나머지 환경 변수 값)
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${SHORT_SHA}'